version: '3'

services:
  express:
    build: ./express
    container_name: ${APP_NAME}_express
    ports: 
      - "3000:3000"
    entrypoint: npm run start
    volumes:
      - ./express/app:/app
  postgres:
    image: postgres
    container_name: ${APP_NAME}_postgres
    restart: always
    user: "1000"
    ports: 
      - "5442:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${APP_NAME}_pgadmin
    restart: "always"
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres